[package]
name = "appendonly"
version = "0.1.0"
authors = ["Andrey Sobol <baskerville@andreysobol.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake2 = "0.9.0"
hex-literal = "0.2.1"
digest = "0.9"